name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Show cargo version
        run: cargo --version
      - name: Fetch
        run: |
          cargo fetch --locked
      - name: Build
        run: |
          cargo build --release --frozen
      - name: Test
        run: |
          cargo test --release --frozen --workspace
